// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Next.js: process.env.NEXT_PUBLIC_* (env no browser)
const SUPABASE_URL = (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_SUPABASE_URL) || (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_URL) || "";
const SUPABASE_PUBLISHABLE_KEY = (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_SUPABASE_ANON_KEY) || (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY) || (typeof process !== "undefined" && process.env?.VITE_SUPABASE_PUBLISHABLE_KEY) || "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Storage seguro para SSR/build: só usa localStorage no browser (evita "localStorage is not defined")
const safeStorage = typeof window !== "undefined" && window.localStorage
  ? window.localStorage
  : {
      getItem: () => null,
      setItem: () => {},
      removeItem: () => {},
    };

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  auth: {
    storage: safeStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});